package cleveres.tricky.cleverestech

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Test
import kotlin.system.measureTimeMillis

class WebServerPerfTest {

    @Test
    fun testPerformance() {
        val arr = JSONArray()
        for (i in 0 until 1000) {
            val obj = JSONObject()
            obj.put("package", "com.example.app$i")
            obj.put("template", "tmpl$i")
            obj.put("keybox", "kb$i")
            val perms = JSONArray()
            for (j in 0 until 50) {
                perms.put("android.permission.PERM$j")
            }
            obj.put("permissions", perms)
            arr.put(obj)
        }
        val jsonStr = arr.toString()

        // Warmup
        for (w in 0 until 10) {
            testOld(jsonStr)
            testNew(jsonStr)
        }

        val timeOld = measureTimeMillis {
            for (i in 0 until 100) {
                testOld(jsonStr)
            }
        }

        val timeNew = measureTimeMillis {
            for (i in 0 until 100) {
                testNew(jsonStr)
            }
        }

        println("BENCHMARK RESULT: Old time: $timeOld ms")
        println("BENCHMARK RESULT: New time: $timeNew ms")
    }

    private val PKG_NAME_REGEX = Regex("^[a-zA-Z0-9_.*]+\$")
    private val TEMPLATE_NAME_REGEX = Regex("^[a-zA-Z0-9_.-]+\$")
    private val KEYBOX_FILENAME_REGEX = Regex("^[a-zA-Z0-9_.-]+\$")
    private val PERMISSIONS_REGEX = Regex("^[a-zA-Z0-9_.,*]+\$")
    private val WHITESPACE_FIND_REGEX = Regex("\\s")

    private fun testOld(jsonStr: String): String {
        val array = JSONArray(jsonStr)
        val sb = java.lang.StringBuilder()
        sb.append("# Generated by WebUI\n")
        for (i in 0 until array.length()) {
            val obj = array.getJSONObject(i)
            val pkg = obj.getString("package")
            val tmpl = obj.optString("template", "null").ifEmpty { "null" }
            val kb = obj.optString("keybox", "null").ifEmpty { "null" }
            val permsArr = obj.optJSONArray("permissions")
            var permsStr = "null"
            if (permsArr != null && permsArr.length() > 0) {
                val list = ArrayList<String>()
                for (j in 0 until permsArr.length()) {
                    list.add(permsArr.getString(j))
                }
                permsStr = list.joinToString(",")
            }
            if (!pkg.matches(PKG_NAME_REGEX)) continue
            if (tmpl != "null" && !tmpl.matches(TEMPLATE_NAME_REGEX)) continue
            if (kb != "null" && !kb.matches(KEYBOX_FILENAME_REGEX)) continue
            if (permsStr != "null" && !permsStr.matches(PERMISSIONS_REGEX)) continue
            if (pkg.contains(WHITESPACE_FIND_REGEX)) continue
            sb.append("$pkg $tmpl $kb $permsStr\n")
        }
        return sb.toString()
    }

    private fun testNew(jsonStr: String): String {
        val array = JSONArray(jsonStr)
        val sb = java.lang.StringBuilder()
        sb.append("# Generated by WebUI\n")
        for (i in 0 until array.length()) {
            val obj = array.getJSONObject(i)
            val pkg = obj.getString("package")
            val tmpl = obj.optString("template", "null").ifEmpty { "null" }
            val kb = obj.optString("keybox", "null").ifEmpty { "null" }
            val permsArr = obj.optJSONArray("permissions")

            val len = permsArr?.length() ?: 0
            val permsStr = if (len > 0) {
                val pSb = StringBuilder()
                pSb.append(permsArr!!.getString(0))
                for (j in 1 until len) {
                    pSb.append(',').append(permsArr.getString(j))
                }
                pSb.toString()
            } else {
                "null"
            }

            if (!pkg.matches(PKG_NAME_REGEX)) continue
            if (tmpl != "null" && !tmpl.matches(TEMPLATE_NAME_REGEX)) continue
            if (kb != "null" && !kb.matches(KEYBOX_FILENAME_REGEX)) continue
            if (permsStr != "null" && !permsStr.matches(PERMISSIONS_REGEX)) continue
            if (pkg.contains(WHITESPACE_FIND_REGEX)) continue

            sb.append(pkg).append(' ')
              .append(tmpl).append(' ')
              .append(kb).append(' ')
              .append(permsStr).append('\n')
        }
        return sb.toString()
    }
}
