version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    groups:
      bouncycastle-security:
        applies-to: security-updates
        patterns:
          - "org.bouncycastle:*"
      bouncycastle:
        applies-to: version-updates
        patterns:
          - "org.bouncycastle:*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
